spring:
  # db connection config
  datasource:
    url: jdbc:mysql://localhost:3306/e-invoice
    username: root
    password: admin123
    initial-size: 2
    min-idle: 2
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    druid:
      username: druid
      password: 1024
      login:
        enabled: false
      method:
        pointcut: com.zzz.platform..*Service.*

  # upload file size
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  # json serialisation config
  jackson:
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      read-enums-using-to-string: true
      fail-on-unknown-properties: false
    default-property-inclusion: always
    date-format: yyyy-MM-dd
    time-zone: GMT+10

  # spring mail config
  mail:
    host: smtp.office365.com
    port: 587
    username: eazyinvoice9900zzz@outlook.com
    password: bcjypmyxhqexiliy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.office365.com
      transport:
        protocol: smtp



# tomcat config，Primarily used to configure access logs (for future error troubleshooting)
server:
  tomcat:
    basedir: ${project.log-directory}/tomcat-logs
    accesslog:
      enabled: true
      max-days: 7
      pattern: "%t %{X-Forwarded-For}i %a %r %s (%D ms) %I (%B byte)"

# RestTemplate config
http:
  pool:
    max-total: 20
    connect-timeout: 60000
    read-timeout: 60000
    write-timeout: 60000
    keep-alive: 60000

# Open API configuration
springdoc:
  swagger-ui:
    enabled: true # Switch
    doc-expansion: none # Disable expansion
    tags-sorter: alpha
  api-docs:
    enabled: true # Switch
knife4j:
  enable: true
  basic:
    enable: false
    username: api # Basic authentication username
    password: 1024 # Basic authentication password

classified-protect:
  # Number of consecutive login failures to lock the account, -1 means no limit, allowing infinite login attempts
  login-max-fail-times: 5
  # Duration of lock after consecutive login failures (in seconds), -1 means no lock, it is recommended to lock for 30 minutes
  login-fail-locked-seconds: 1800
  # Password complexity enabled (default complexity: at least three types of characters, minimum 8 characters), true to enable, false to disable, it is recommended to enable
  password-complexity-enabled: true

sa-token:
  token-name: x-access-token
  # Minimum token active frequency (in seconds), if the token has not accessed the system within this time, it will be frozen, default -1 means no restriction, never freeze
  active-timeout: 1800
  # Token validity period (in seconds), 1 day (86400 seconds), -1 means permanently valid
  timeout: 86400
  token-style: simple-uuid

cache:
  # key expiration time in cache
  duration: 30
  # maximum key in cache
  maximum: 100