spring:
  # db connection config
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/xxx
    username: root
    password: zzz9900
    initial-size: 2
    min-idle: 2
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat
    druid:
      username: druid
      password: 1024
      login:
        enabled: false
      method:
        pointcut: net.lab1024.sa..*Service.*

  # json serialisation config
  jackson:
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      read-enums-using-to-string: true
      fail-on-unknown-properties: false
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# tomcat config，Primarily used to configure access logs (for future error troubleshooting)
server:
  tomcat:
    basedir: ${project.log-directory}/tomcat-logs
    accesslog:
      enabled: true
      max-days: 7
      pattern: "%t %{X-Forwarded-For}i %a %r %s (%D ms) %I (%B byte)"

# RestTemplate config
http:
  pool:
    max-total: 20
    connect-timeout: 50000
    read-timeout: 50000
    write-timeout: 50000
    keep-alive: 300000

classified-protect:
  # Number of consecutive login failures to lock the account, -1 means no limit, allowing infinite login attempts
  login-max-fail-times: 5
  # Duration of lock after consecutive login failures (in seconds), -1 means no lock, it is recommended to lock for 30 minutes
  login-fail-locked-seconds: 1800
  # Password complexity enabled (default complexity: at least three types of characters, minimum 8 characters), true to enable, false to disable, it is recommended to enable
  password-complexity-enabled: true

sa-token:
  # Minimum token active frequency (in seconds), if the token has not accessed the system within this time, it will be frozen, default -1 means no restriction, never freeze
  active-timeout: 1800
  # Token validity period (in seconds), 1 day (86400 seconds), -1 means permanently valid
  timeout: 86400
