spring:
  # db connection config
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/xxx
    username: root
    password: zzz9900
    initial-size: 2
    min-idle: 2
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat
    druid:
      username: druid
      password: 1024
      login:
        enabled: false
      method:
        pointcut: net.lab1024.sa..*Service.*

  # json serialisation config
  jackson:
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      read-enums-using-to-string: true
      fail-on-unknown-properties: false
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# tomcat config，Primarily used to configure access logs (for future error troubleshooting)
server:
  tomcat:
    basedir: ${project.log-directory}/tomcat-logs
    accesslog:
      enabled: true
      max-days: 7
      pattern: "%t %{X-Forwarded-For}i %a %r %s (%D ms) %I (%B byte)"

# RestTemplate config
http:
  pool:
    max-total: 20
    connect-timeout: 50000
    read-timeout: 50000
    write-timeout: 50000
    keep-alive: 300000