# ????: ???????
project:
  name: platform
  log-directory: ../${project.name}/${spring.profiles.active}

# ?????url???
server:
  port: 9900
  servlet:
    context-path: /

# ??
spring:
  profiles:
    active: dev

# swagger??
swagger:
  host: localhost:${server.port}

upbrainsai:
  token: wRRxw-vrrrL0Agi9oCx1lof4O7bmY8DMYwwqrXkVVEuxi4C9mV9czoV6P7i2
#logging:
#  level:
#    org:
#      springframework: DEBUG
#    io:
#      springfox: DEBUG
